### ISSUE TITLE
Incorrect visualisation of metadata blocks/columns 

### ISSUE THREAD

**Issue by HarryHung** [ChrispinChaguza/RCandy#4]
When using the sample data, I could plot the basic visualisation with RCandy.
```
library(RCandy)

tree.file <- system.file("extdata", "ST320.final_tree.tre", package = "RCandy", mustWork = TRUE)
metadata.file <- system.file("extdata", "ST320.tsv", package = "RCandy", mustWork = TRUE)
gubbins.gff <- system.file("extdata", "ST320.recombination_predictions.gff", package = "RCandy", 
                           mustWork = TRUE)
ref.genome.gff <- system.file("extdata", "Hungary19A-6.gff", package = "RCandy", 
                              mustWork = TRUE)


RCandyVis(tree.file.name = tree.file, midpoint.root = TRUE, ladderize.tree.right = TRUE, 
          taxon.metadata.file = metadata.file, taxon.metadata.columns = c("Source", "Country"))
```
![image](https://user-images.githubusercontent.com/4848896/162175799-71b3e7c1-887d-4609-9fa1-fd4dade5aad9.png)

However, when I try to plot with my selected data as test run, most sections of the metadata blocks/columns does not have any colour, despite the legend shows colours are assigned to them. 

(the actual file path assigned to data.folder is removed)
```
library(RCandy)

data.folder <- file.path("PATH", "TO", "FILE")

  
tree.file <- file.path(data.folder, "GPSC6-BWA.final_tree.tre")
metadata.file <- read.csv(file=file.path(data.folder, "Meta_GPSC6-30.csv"))
gubbins.gff <- file.path(data.folder, "GPSC6-BWA.recombination_predictions.gff")
ref.genome.gff <- file.path(data.folder, "GPSC6_reference.gff")


RCandyVis(tree.file.name = tree.file, midpoint.root = TRUE, ladderize.tree.right = TRUE, 
          taxon.metadata.file = metadata.file, 
          taxon.metadata.columns = c("In_Silico_serotype", 'Country_x'),
          taxon.id.column = "lane_id")

```
![image](https://user-images.githubusercontent.com/4848896/162176801-553c5f7d-f182-476d-a4b4-e512ed8815d9.png)

I could confirm the column "lane_id" is the first column in the metadata file and contains the same taxon name as in the tree file, I believe it could be demonstrated by the result of using the same tree and metadata file on [phandango](https://jameshadfield.github.io/phandango/):
![image](https://user-images.githubusercontent.com/4848896/162177852-9f46e5ca-4548-4dcb-9b06-82b597f6d18a.png)

Here is the content of column "In_Silico_serotype"
```
> table(metadata.file$In_Silico_serotype)

11A  14 23F 24F  9V 
  3  12   1   6   8 
```

Here is the content of column "Country_x"
```
> table(metadata.file$Country_x)

   ARGENTINA      BELARUS       BRAZIL     CAMBODIA        CHINA       FRANCE        INDIA       ISRAEL  NEW ZEALAND         PERU SOUTH AFRICA 
           4            2            3            2            1            6            1            2            1            2            4 
         USA 
           2 
```

Here are extracts from the structure of metadata.file after reading the csv:
```
> str(metadata.file)
'data.frame':	30 obs. of  174 variables:
 $ lane_id                          : chr  "11657_4_75" "12291_2_2" "12291_6_92" "14257_1_29" ..
...
$ Country_x                        : chr  "PERU" "PERU" "SOUTH AFRICA" "SOUTH AFRICA" ...
...
$ In_Silico_serotype               : chr  "14" "14" "14" "9V" ...
...
```

As there is no warning when I run the code, I am not sure what went wrong. Please let me know if you need any extra information. 

Thank you!

**Comment by HarryHung** [comment]
@ChrispinChaguza  Thank you for your assistance. I have sent you the tree and metadata.

**Comment by HarryHung** [comment]
@wmiellet  Thanks for the tips!

I encountered some issues doing it this way but resolved it after some modifications. Details below:

Running `metadata.file <- file.path(data.folder, "Meta_GPSC6-30.csv")` results in the following error:
```
Error in load.taxon.metadata(taxon.metadata.file = taxon.metadata.file,  : 
  Column for taxon names not found in the metadata file or data frame
```

I looked into `load.taxon.metadata` and it seems it is expecting a tsv instead of csv based on its function arguments:
```
function (taxon.metadata.file, taxon.metadata.columns = NULL, 
  taxon.names = NULL, taxon.id.column = NULL, include.first.col = FALSE, 
  taxon.metadata.delimeter = "\t") 
```

So, I try to convert my csv into tsv but faced with the following error:
```
Error in read.table(taxon.metadata.file, header = TRUE, sep = taxon.metadata.delimeter,  : 
  more columns than column names
```
It seems to be caused by my metadata contains a lot of symbols and `read.table` does not handle it well, based on this 
[StackOverflow thread](https://stackoverflow.com/questions/24028093/what-does-the-more-columns-than-column-names-error-mean). In which, they also suggest switching to read.csv instead of read.table. 

So I modify the `load.taxon.metadata` using `trace("load.taxon.metadata", edit=TRUE)` and change line 7 - 9 from
```
            tmp.taxon.data <- as_tibble(read.table(taxon.metadata.file, 
                header = TRUE, sep = taxon.metadata.delimeter, 
                comment.char = "?"))
```
to 
```
            tmp.taxon.data <- as_tibble(read.csv(taxon.metadata.file))
```
After modifying the `load.taxon.metadata`, it seems the medata blocks/columns visualisation work fine now.
![image](https://user-images.githubusercontent.com/4848896/174063483-b8f18202-86c3-4964-be7f-b83c0f88f250.png)

Perhaps @ChrispinChaguza you could consider adding an option to use `read.csv` in `load.taxon.metadata`?

**Comment by ChrispinChaguza** [comment]
Thank you @HarryHung @HarryHung for the suggested changes. I have changed read.table to fread in the load.taxon.metadata.R function, so it should work now.

**Comment by HarryHung** [comment]
Thank for the update @ChrispinChaguza. I could confirm the fread update resolved the issue.

I would suggest adding to your README that `taxon.metadata.delimeter`uses `\t` by default therefore supporting tsv, but can pass in `taxon.metadata.delimeter = ","` to use it on csv. 

Also, should it be `taxon.metadata.delimiter` instead of `taxon.metadata.delimeter`?

Thank you for all your hard work!

**Comment by ChrispinChaguza** [comment]
@HarryHung I have made the suggested changes. Thank you.

**Comment by HarryHung** [comment]
@ChrispinChaguza  Thanks for the update.

Just a bit typo in the updated README I think:

> By default the columns in the metadata file are assumed assummed to be separated by tabs "\t", but this can be changed by passing this argument taxon.metadata.delimeter = "," when working with a file with column separated values.

Should be this?

> By default the columns in the metadata file are assumed to be separated by tabs "\t", but this can be changed by passing this argument taxon.metadata.delimiter = "," when working with a file with comma separated values.

Thanks again!

**Comment by ChrispinChaguza** [comment]
@HarryHung indeed, I have corrected the typo.

**Comment by HarryHung** [comment]
Thank you!
